### ISSUE TITLE
crash with latest ae2 and ae2wtlib

### ISSUE THREAD

**Issue by Chuunkyz** [ProjectET/AE2Things#1]
i can see 1.0.0-beta1 in the name so is intended to run with ae2 1.0.0-beta 1 ? i have beta3 of ae2 rn, as well as the corresponding version for wireless terminals

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'ae2'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$fjn000$catchFabricInit(class_310.java:25978)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: appeng/api/implementations/IUpgradeInventory
	at io.github.projectet.ae2things.item.AETItems.<clinit>(AETItems.java:14)
	at io.github.projectet.ae2things.AE2Things.onAe2Initialized(AE2Things.java:51)
	at appeng.core.AppEngBase.notifyAddons(AppEngBase.java:311)
	at appeng.core.AppEngClient.<init>(AppEngClient.java:128)
	at appeng.core.AppEngClientStartup.onInitializeClient(AppEngClientStartup.java:12)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more
Caused by: java.lang.ClassNotFoundException: appeng.api.implementations.IUpgradeInventory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 19 more

**Comment by ProjectET** [comment]
No it works with beta.2, i've got a new version uploaded that works with beta.3 but its still getting approved by curseforge

**Comment by ProjectET** [comment]
new update has finally been approved
