### ISSUE TITLE
Crash while dragging items in the inventory or anywhere.

### ISSUE THREAD

**Issue by frikinjay** [ProjectET/AE2Things#2]
Cursed indeed.
```
Description: Container click

java.lang.IndexOutOfBoundsException: Index -999 out of bounds for length 46
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18)
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.util.collection.DefaultedList.get(DefaultedList:47)
	at net.minecraft.screen.ScreenHandler.handler$zem000$CLONE(ScreenHandler:34)
	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler:342)
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:284)
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager:417)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen:566)
	at net.minecraft.client.gui.screen.ingame.CraftingScreen.onMouseClick(CraftingScreen:109)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseReleased(HandledScreen:526)
	at net.minecraft.client.Mouse.method_1605(Mouse:96)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:491)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:96)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:195)
	at net.minecraft.client.util.Window.swapBuffers(Window:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1142)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.class_2371.get(class_2371.java:47)
	at net.minecraft.class_1703.handler$zem000$CLONE(io/github/projectet/ae2things/mixin/CursedInternalSlotMixin.java [ae2things.mixins.json]:34)
	at net.minecraft.class_1703.method_30010(class_1703.java:342)
	at net.minecraft.class_1703.method_7593(class_1703.java:284)
	at net.minecraft.class_636.method_2906(class_636.java:417)
	at net.minecraft.class_465.method_2383(class_465.java:566)
	at net.minecraft.class_479.method_2383(class_479.java:109)
	at net.minecraft.class_465.method_25406(class_465.java:526)
	at net.minecraft.class_312.method_1605(class_312.java:96)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:96)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:101)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:195)

**Comment by ProjectET** [comment]
Fixed in: 697c4f91b4b430a7336837c71f10fadbbc48c047
