### ISSUE TITLE
Server crash when opening the Advanced Inscriber

### ISSUE THREAD

**Issue by 4nner** [ProjectET/AE2Things#5]
This is probably due to AE2's new menu.

Using:
AE2 10.1.0-beta.1
AE2Things 1.0.1-beta.3

Error:
```
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'boolean io.github.projectet.ae2things.gui.advancedInscriber.AdvancedInscriberMenu.isServer()'
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
        at io.github.projectet.ae2things.gui.advancedInscriber.AdvancedInscriberMenu.standardDetectAndSendChanges(AdvancedInscriberMenu.java:62) ~[AE2Things-1.0.1-beta.3.jar:?]
        at appeng.menu.implementations.UpgradeableMenu.sendContentUpdates(UpgradeableMenu.java:126) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
        at net.minecraft.screen.ScreenHandler.addListener(ScreenHandler:131) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.onScreenHandlerOpened(ServerPlayerEntity:401) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.openHandledScreen(ServerPlayerEntity:1040) ~[?:?]
        at appeng.menu.implementations.MenuTypeBuilder.open(MenuTypeBuilder.java:167) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
        at appeng.menu.MenuOpener.open(MenuOpener.java:55) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
        at io.github.projectet.ae2things.block.BlockAdvancedInscriber.onActivated(BlockAdvancedInscriber.java:65) ~[AE2Things-1.0.1-beta.3.jar:?]
        at appeng.block.AEBaseEntityBlock.onUse(AEBaseEntityBlock.java:228) ~[appliedenergistics2-10.1.0-beta.1.jar:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1057) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by ProjectET** [comment]
fixed in ea98599d54752fbd5a4c2c65760b192ac23d1ac9. Check curseforge or modrinth for latest release
